export const booksData = [
  {
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    publisher: 'Prentice Hall',
    year: 2008,
    ISBN: '978-0132350884',
    language: 'English',
    format: 'Paperback',
    pages: 464,
    category: 'Software Engineering',
    imgURL: '../../clean_code.jpg',
  },
  {
    title: 'The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win',
    author: 'Gene Kim, Kevin Behr, and George Spafford',
    publisher: 'IT Revolution Press',
    year: 2013,
    ISBN: '978-0988262591',
    language: 'English',
    format: 'Paperback',
    pages: 376,
    category: 'DevOps',
    imgURL: '../../phoenix_project.jpg',
  },
  {
    title:
      'Designing Data-Intensive Applications: The Big Ideas Behind Reliable, Scalable, and Maintainable Systems',
    author: 'Martin Kleppmann',
    publisher: "O'Reilly Media",
    year: 2017,
    ISBN: '978-1449373320',
    language: 'English',
    format: 'Paperback',
    pages: 616,
    category: 'Database Systems',
    imgURL: '../../designing-data.jpg',
  },
  {
    title: 'Code Complete: A Practical Handbook of Software Construction',
    author: 'Steve McConnell',
    publisher: 'Microsoft Press',
    year: 2004,
    ISBN: '978-0735619678',
    language: 'English',
    format: 'Paperback',
    pages: 960,
    category: 'Software Engineering',
    imgURL: '../../code_complete.jpg',
  },
  {
    title: 'The Art of Computer Programming, Volumes 1-4A Boxed Set',
    author: 'Donald E. Knuth',
    publisher: 'Addison-Wesley Professional',
    year: 2011,
    ISBN: '978-0321751041',
    language: 'English',
    format: 'Hardcover',
    pages: 3168,
    category: 'Algorithms',
    imgURL: '../../art_of_computer.png',
  },
  {
    title: 'Head First Design Patterns: A Brain-Friendly Guide',
    author: 'Eric Freeman, Elisabeth Robson, Bert Bates, and Kathy Sierra',
    publisher: "O'Reilly Media",
    year: 2004,
    ISBN: '978-0596007126',
    language: 'English',
    format: 'Paperback',
    pages: 694,
    category: 'Software Design Patterns',
    imgURL: '../../design_patterns.jpg',
  },
  {
    title: "The Clean Architecture: A Craftsman's Guide to Software Structure and Design",
    author: 'Robert C. Martin',
    publisher: 'Prentice Hall',
    year: 2017,
    ISBN: '978-0134494166',
    language: 'English',
    format: 'Hardcover',
    pages: 432,
    category: 'Software Architecture',
    imgURL: '../../clean_arch.jpg',
  },
];
